In [1]:
import utils.data as data
import utils.stats as stats
import numpy as np
import matplotlib.pyplot as plt


In [2]:
dataset = "ugr16"
filename = "raw.csv"

In [3]:
def tmp():
    df = data.load_data(dataset, filename)
    print(df)

    # compute the packet counts
    timestamps, pkt_counts = stats.pkt_count(df, time_unit_exp=1, verbose=True)

    # compute the hurst exponent of the packet counts
    hurst = stats.hurst(pkt_counts)

    print("Hurst exponent: {:.2f}".format(hurst))

    return 

tmp()

Loading data from:
	data/ugr16/raw.csv
Number of packets: 1000000
Trace duration: 1342.636 seconds
             srcip      dstip  srcport  dstport proto      time       td  pkt  \
0       1730436467  719036359        0        0  ICMP     0.000  305.636   62   
1       1730436466  719036359        0        0  ICMP     0.000  305.636   62   
2       3627282195  719036341        0        0  ICMP     0.636  300.000   31   
3        607268605  719036341        0        0  ICMP     0.640  299.996   31   
4       3628038305  719036341        0        0  ICMP     0.640  299.996   31   
...            ...        ...      ...      ...   ...       ...      ...  ...   
999645  2403862665  719034994       53    53469   UDP  1342.636    0.000    1   
999644  2403862665  719034994       53    47388   UDP  1342.636    0.000    1   
999643  2403862665  719034994       53    47209   UDP  1342.636    0.000    1   
999641  2403862665  719034994       53    46968   UDP  1342.636    0.000    1   
999999  17

In [4]:
def packet_count_cmp(time_unit_exp=1):
    dataset = "ugr16"
    filename = "raw.csv"

    # Load the data
    df = data.load_data(dataset, filename, verbose=False)

    # Compute the packet counts and its hurst exponent
    timestamps, timeseries = stats.pkt_count(df, time_unit_exp)

    # hurst = stats.hurst(packet_counts)

    # ts = np.random.normal(0, 1, 10000)
    ts = timeseries
    print(ts[:10])

    acf = stats.autocorr(ts)
    print(f"Autocorrelation function: {acf[:20]}")
    print(f"Autocorrelation function: {acf[-20:]}")

    hurst = stats.hurst(ts)
    print(f"Hurst exponent: {hurst}")

    fig, axes = plt.subplots(2, 1, figsize=(10, 10))
    axes[0].plot(timestamps, timeseries, label="raw")
    axes[0].set_xlabel("Time (s)")
    axes[0].set_ylabel("Packet count")
    axes[0].set_title("Packet count over time")

    axes[1].plot(acf, label="raw")
    axes[1].set_xlabel("Lag")
    axes[1].set_ylabel("Autocorrelation")
    axes[1].set_title("Autocorrelation function")


    dataset = "ugr16"
    filename = "syn.csv"

    # Load the data
    df = data.load_data(dataset, filename, verbose=False)

    # Compute the packet counts and its hurst exponent
    timestamps, timeseries = stats.pkt_count(df, time_unit_exp)

    # hurst = stats.hurst(packet_counts)

    # ts = np.random.normal(0, 1, 10000)
    ts = timeseries
    print(ts[:10])

    acf = stats.autocorr(ts)
    print(f"Autocorrelation function: {acf[:20]}")
    print(f"Autocorrelation function: {acf[-20:]}")

    hurst = stats.hurst(ts)
    print(f"Hurst exponent: {hurst}")

    axes[0].plot(timestamps, timeseries, label="syn")
    axes[0].legend()
    axes[1].plot(acf, label="syn")
    axes[1].legend()

    plt.show()

packet_count_cmp(time_unit_exp=-4)


Loading data from:
	data/ugr16/raw.csv
Number of packets: 1000000
Trace duration: 1342.636 seconds
Time unit 1.0e-04 has 204497 bars
[2. 1. 2. 1. 1. 1. 1. 1. 1. 1.]
Autocorrelation function: [0.02287702 0.02287702 0.01813236 0.01748977 0.0167599  0.0154792
 0.01595917 0.01707201 0.01727674 0.01667817 0.01667106 0.01578865
 0.01545843 0.01536385 0.01556951 0.01628969 0.01609009 0.01605658
 0.0161872  0.01586012]
Autocorrelation function: [2.22709229e-06 2.23098580e-06 2.21930525e-06 2.21151821e-06
 2.19594414e-06 4.22057349e-06 2.17258303e-06 2.18037007e-06
 2.16868952e-06 2.18037007e-06 2.15700896e-06 2.15311544e-06
 2.14143489e-06 2.13754137e-06 2.12196730e-06 2.11418026e-06
 2.08692564e-06 4.08819388e-06 2.04409694e-06 4.05704574e-06]
Hurst exponent: 0.0006864338679610211
Loading data from:
	data/ugr16/syn.csv
Number of packets: 1051363
Trace duration: 1847.78589625 seconds
Time unit 1.0e-04 has 988360 bars
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
def byte_count_cmp(time_unit_exp=1):
    dataset = "ugr16"
    filename = "raw.csv"

    # Load the data
    df = data.load_data(dataset, filename, verbose=False)

    # Compute the packet counts and its hurst exponent
    timestamps, timeseries = stats.byte_count(df, time_unit_exp)

    # hurst = stats.hurst(packet_counts)

    # ts = np.random.normal(0, 1, 10000)
    ts = timeseries
    print(ts[:10])

    acf = stats.autocorr(ts)
    print(f"Autocorrelation function: {acf[:20]}")
    print(f"Autocorrelation function: {acf[-20:]}")

    hurst = stats.hurst(ts)
    print(f"Hurst exponent: {hurst}")

    fig, axes = plt.subplots(2, 1, figsize=(10, 10))
    axes[0].plot(timestamps, timeseries, label="raw")
    axes[0].set_xlabel("Time (s)")
    axes[0].set_ylabel("Byte count")
    axes[0].set_title("Byte count over time")

    axes[1].plot(acf, label="raw")
    axes[1].set_xlabel("Lag")
    axes[1].set_ylabel("Autocorrelation")
    axes[1].set_title("Autocorrelation function")


    dataset = "ugr16"
    filename = "syn.csv"

    # Load the data
    df = data.load_data(dataset, filename, verbose=False)

    # Compute the packet counts and its hurst exponent
    timestamps, timeseries = stats.byte_count(df, time_unit_exp)

    # hurst = stats.hurst(packet_counts)

    # ts = np.random.normal(0, 1, 10000)
    ts = timeseries
    print(ts[:10])

    acf = stats.autocorr(ts)
    print(f"Autocorrelation function: {acf[:20]}")
    print(f"Autocorrelation function: {acf[-20:]}")

    hurst = stats.hurst(ts)
    print(f"Hurst exponent: {hurst}")

    axes[0].plot(timestamps, timeseries, label="syn")
    axes[0].legend()
    axes[1].plot(acf, label="syn")
    axes[1].legend()

    plt.show()

byte_count_cmp(time_unit_exp=-3)


Loading data from:
	data/ugr16/raw.csv
Number of packets: 1000000
Trace duration: 1342.636 seconds
Time unit 1.0e-03 has 204497 bars
[ 124   31   62   31 6501 9008  204  120   62   62]
Autocorrelation function: [0.05118831 0.05118831 0.02409027 0.02135746 0.02438005 0.01290908
 0.008764   0.00967681 0.00923802 0.01087916 0.00929439 0.00760488
 0.01091301 0.05908469 0.00495111 0.00536919 0.0053133  0.00575574
 0.00659733 0.00928265]
Autocorrelation function: [2.08304972e-07 1.95225935e-07 4.05556307e-07 1.21491032e-07
 1.88862849e-07 2.11553932e-07 1.82663288e-07 6.18544659e-07
 4.30704550e-07 2.59916822e-07 3.12420880e-07 4.30178118e-07
 3.74557066e-07 2.92122409e-07 8.02699169e-06 5.76668501e-06
 3.16605082e-08 5.62062955e-08 2.81920817e-08 1.09922439e-07]
Hurst exponent: 0.0018250254340799867
Loading data from:
	data/ugr16/syn.csv
Number of packets: 1051363
Trace duration: 1847.78589625 seconds
Time unit 1.0e-03 has 658374 bars
[123 135 155 113 116 153 158 162 133 128]
